worker_processes auto;
events {}

stream {
    # 1. Gelen şifreli TLS paketinin el sıkışmasından SNI (domain) bilgisini oku
    ssl_preread on;

    # 2. SNI adına göre isteğin hangi ülkenin upstream grubuna gideceğini belirle
    map $ssl_preread_server_name $hetzner_target {
        google.com          germany_backend;
        www.google.com      finland_backend;
        default             finland_backend; # Eşleşme olmazsa varsayılan olarak Finlandiya'ya atsın
    }

    # 3. ALMANYA SUNUCUSU - Port Grupları
    upstream germany_backend {
        server 5.75.192.195:2777;
        server 5.75.192.195:7721;
    }

    # 4. FİNLANDİYA SUNUCUSU - Port Grupları
    upstream finland_backend {
        server 65.109.221.193:2777;
        server 65.109.221.193:7721;
    }

    # 5. Cloud Run'ın dış dünyayı dinlediği ana kapı
    server {
        listen 8080;
        proxy_pass $hetzner_target;
        
        # Bağlantıların kopmaması ve akıcı olması için timeout sürelerini geniş tutuyoruz
        proxy_connect_timeout 5s;
        proxy_timeout 10m;
    }
}
