worker_processes auto;
events {}

http {
    # gRPC için port tanımı
    upstream grpc_backend {
        server 65.109.221.193:2777;
    }

    # WebSocket için port tanımı
    upstream ws_backend {
        server 65.109.221.193:7721;
    }

    server {
        listen 8080;

        # 1. Gelen istek gRPC ise burası çalışır
        location / {
            grpc_pass grpc://grpc_backend;
        }

        # 2. Vless/Tun gibi WebSocket (WS) yolları için burası çalışır
        location /vless/Tun {
            proxy_pass http://ws_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}
